name: Create Github Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-gh-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Get Release Version
      id: version
      shell: pwsh
      run: ([xml](Get-Content ./dns-updater.csproj)).Project.PropertyGroup.Version
    - name: publish windows
      run: dotnet publish -r win-x64 -o ./publish/win-x64 ./dns-updater.csproj
    - name: publish linux
      run: dotnet publish -r linux-x64 -o ./publish/linux-x64 ./dns-updater.csproj
    - name: publish linux-musl
      run: dotnet publish -r linux-musl-x64 -o ./publish/linux-musl-x64 ./dns-updater.csproj
    - name: Changelog
      uses: Bullrich/generate-release-changelog@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}
    - name: Create GH Release
      uses: softprops/action-gh-release@v2
      id: create_release
      with:
        draft: false
        prerelease: false
        generate_release_notes: true
        make_latest: true
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 
        asset_name: dns-updater-win-x64.exe
        asset_content_type: application/octet-stream
    - name: upload linux-musl artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: 
        asset_name: dns-updater-linux-musl-x64
        asset_content_type: application/x-sharedlib
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./publish/linux-x64/dns-updater
        asset_name: dns-updater-linux-x64
        asset_content_type: application/x-sharedlib
    